kind: Service                             
apiVersion: v1
metadata:
  name: sev_ronco
  labels:
    app: ronco
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: ronco                    
  type: LoadBalancer    
